name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    needs: create-gerbers
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.6 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo_dir

      - name: Initialize
        working-directory: repo_dir/zephyr_container
        run: |
          west init -l ./zephyr_project
          west update

      - name: Build firmware
        working-directory: repo_dir/zephyr_container/zephyr_project
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Twister Tests
        working-directory: repo_dir/zephyr_container/zephyr_project
        run: |
          west twister -T tests --integration

  create-gerbers:
    runs-on: ubuntu-22.04
    container: 
      image: kicad/kicad:7.0
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo_dir

      - name: Initialize
        working-directory: repo_dir/KiCadFiles
        run: |
          mkdir -p ProductionFiles

      - name: Create Gerbers
        working-directory: repo_dir/KiCadFiles
        run: |
          kicad-cli pcb export gerbers --output "./ProductionFiles" --layers F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts --no-protel-ext ./DiceTower.kicad_pcb

      - name: Zip Gerbers
        working-directory: repo_dir/KiCadFiles/ProductionFiles
        run: |
          zip -r gerbers.zip ./*
      
      - name: Archive Gerbers
        uses: actions/upload-artifact@v3
        with:
          name: gerbers
          path: repo_dir/KiCadFiles/ProductionFiles/gerbers.zip
